### ISSUE TITLE
any support on foreignkey auto-generate?

### ISSUE THREAD

**Issue by ws6** [jcteague/autofixturejs#2]
is there any furture plan to support auto foreign key generation?
that would be great.

**Comment by jcteague** [comment]
@ws6 not sure what you have in mind here.  this is just used to autogenerate fields.  Are you suggesting we recurse further into an object?

**Comment by jcteague** [comment]
@ws6 You can populated nested objects using other fixtures.  Is that what you meant?

``` Javascript
Factory.define('User',[
    'first_name',

]);

Factory.define('Order',[
    'id'.asNumber(),
    'order_date'.asDate()
    'user'.fromFixture('User')
]);
```
